### PR TITLE
rule `zombiePiglinTracingFix`

### PR DESCRIPTION
**Pull request by Hendrix-Shen**
Please refer to #3 for details.
Thanks @Fallen-Breath for the suggestion!

### CODE REVIEW

**Comment by fxmorin** [comment]
Is there a bug report for this? Would be nice to include it

**Comment by Hendrix-Shen** [comment]
Sorry, I don't know it, I'm look for it too.

**Comment by fxmorin** [comment]
What do you mean by Use 1.13 btw?

**Comment by Fallen-Breath** [comment]
> Is there a bug report for this? Would be nice to include it

https://bugs.mojang.com/browse/MC-202249

See `net.minecraft.world.entity.LivingEntity#hasLineOfSight` (mojang mapping) for how mojang fixes this

> What do you mean by Use 1.13 btw?

His previous impl is porting the 1.13- raytrace 200blocks limit

https://github.com/fxmorin/carpet-fixes/blob/9359d78e86882a4e9029c17cfb1d8380707a64ea/src/main/java/carpetfixes/mixins/entityFixes/LivingEntity_VisibilityCheckMixin.java#L30-L38

**Comment by fxmorin** [comment]
Oh sick so it just got fixed.
I'll keep his change till 1.17

**Pull request merged**
